In [1]:
import pandas as pd
import datetime

In [2]:

def format_date(date_str):
    """
    Converts a string 'YYYY-MM-DD' to ISO format.
    """
    dt = datetime.datetime.strptime(date_str, '%Y-%m-%d')
    return dt.strftime('%Y-%m-%dT00:00:00.000-00:00')

In [3]:
datetime.datetime.strptime('el 02 del 2025', 'el %m del %Y')

datetime.datetime(2025, 2, 1, 0, 0)

In [ ]:
renewables_df = pd.read_excel('./data/raw/UCO_UCOME_HVO_prices.xlsx')

In [5]:
renewables_df

,Unnamed: 0,HVO (Class II) fob ARA range,Unnamed: 2,Ucome fob ARA range,Unnamed: 4,UCO ex-works ARA range,Unnamed: 6,UCO fob ARA range,Unnamed: 8,UCO (hydrotreating) fob ARA range,Unnamed: 10,UCO cif ARA,Unnamed: 12
0,NaN,HVO (hydrotreated vegetable oil) fob ARA range...,NaN,Biodiesel UCOME (used cooking oil) RED ARA ran...,NaN,"UCO ex-works ARA range (USD/t), London close, ...",NaN,"UCO (used cooking oil) fob ARA, London close, ...",NaN,"RED UCO (hydrotreating) fob ARA range, London ...",NaN,"UCO (used cooking oil) cif ARA USD/t, London c...",NaN
1,Date,Timing,Price,Timing,Price,Timing,Price,Timing,Price,Timing,Price,Timing,Price
2,2026-04-23 00:00:00,prompt,3098.75,prompt,1529.96,prompt,1259.225,prompt,1265,prompt,1295,prompt,1140
3,2026-04-22 00:00:00,prompt,3142.72,prompt,1550.07,prompt,1259.815,prompt,1265,prompt,1295,prompt,1140
4,2026-04-21 00:00:00,prompt,2922.44,prompt,1561.5,prompt,1263.515,prompt,1245,prompt,1285,prompt,1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258,2021-04-30 00:00:00,prompt,1983.18,prompt,1609.77,prompt,1311.2,NaN,NaN,NaN,NaN,prompt,1210
1259,2021-04-29 00:00:00,prompt,1987.52,prompt,1607.19,prompt,1320.735,NaN,NaN,NaN,NaN,prompt,1190
1260,2021-04-28 00:00:00,prompt,1982.93,prompt,1605.45,prompt,1312.605,NaN,NaN,NaN,NaN,prompt,1190
1261,2021-04-27 00:00:00,prompt,1968.09,prompt,1591.75,prompt,1310.39,NaN,NaN,NaN,NaN,prompt,1175
1262,2021-04-26 00:00:00,prompt,1965.05,prompt,1568.95,prompt,1310.39,NaN,NaN,NaN,NaN,prompt,1175

In [6]:
renewables_df.columns

Index(['Unnamed: 0', 'HVO (Class II) fob ARA range', 'Unnamed: 2',
       'Ucome fob ARA range', 'Unnamed: 4', 'UCO ex-works ARA range',
       'Unnamed: 6', 'UCO fob ARA range', 'Unnamed: 8',
       'UCO (hydrotreating) fob ARA range', 'Unnamed: 10', 'UCO cif ARA',
       'Unnamed: 12'],
      dtype='object')

In [7]:
renewables_df.columns = ['Date', 'HVO (Class II) fob ARA range', 'HVO_class_II_fob_ARA',
       'Ucome fob ARA range', 'Ucome_fob_ARA', 'UCO ex-works ARA range',
       'UCO_exw_ARA', 'UCO fob ARA range', 'UCO_fob_ARA',
       'UCO (hydrotreating) fob ARA range', 'UCO_(hydrotreating)_fob_ARA', 'UCO cif ARA',
       'UCO_cif_ARA']

In [8]:
renewables_df

,Date,HVO (Class II) fob ARA range,HVO_class_II_fob_ARA,Ucome fob ARA range,Ucome_fob_ARA,UCO ex-works ARA range,UCO_exw_ARA,UCO fob ARA range,UCO_fob_ARA,UCO (hydrotreating) fob ARA range,UCO_(hydrotreating)_fob_ARA,UCO cif ARA,UCO_cif_ARA
0,NaN,HVO (hydrotreated vegetable oil) fob ARA range...,NaN,Biodiesel UCOME (used cooking oil) RED ARA ran...,NaN,"UCO ex-works ARA range (USD/t), London close, ...",NaN,"UCO (used cooking oil) fob ARA, London close, ...",NaN,"RED UCO (hydrotreating) fob ARA range, London ...",NaN,"UCO (used cooking oil) cif ARA USD/t, London c...",NaN
1,Date,Timing,Price,Timing,Price,Timing,Price,Timing,Price,Timing,Price,Timing,Price
2,2026-04-23 00:00:00,prompt,3098.75,prompt,1529.96,prompt,1259.225,prompt,1265,prompt,1295,prompt,1140
3,2026-04-22 00:00:00,prompt,3142.72,prompt,1550.07,prompt,1259.815,prompt,1265,prompt,1295,prompt,1140
4,2026-04-21 00:00:00,prompt,2922.44,prompt,1561.5,prompt,1263.515,prompt,1245,prompt,1285,prompt,1140
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1258,2021-04-30 00:00:00,prompt,1983.18,prompt,1609.77,prompt,1311.2,NaN,NaN,NaN,NaN,prompt,1210
1259,2021-04-29 00:00:00,prompt,1987.52,prompt,1607.19,prompt,1320.735,NaN,NaN,NaN,NaN,prompt,1190
1260,2021-04-28 00:00:00,prompt,1982.93,prompt,1605.45,prompt,1312.605,NaN,NaN,NaN,NaN,prompt,1190
1261,2021-04-27 00:00:00,prompt,1968.09,prompt,1591.75,prompt,1310.39,NaN,NaN,NaN,NaN,prompt,1175
1262,2021-04-26 00:00:00,prompt,1965.05,prompt,1568.95,prompt,1310.39,NaN,NaN,NaN,NaN,prompt,1175

In [9]:
renewables_df = renewables_df[2:]
renewables_df.reset_index(drop=True, inplace=True)

In [10]:
renewables_df

,Date,HVO (Class II) fob ARA range,HVO_class_II_fob_ARA,Ucome fob ARA range,Ucome_fob_ARA,UCO ex-works ARA range,UCO_exw_ARA,UCO fob ARA range,UCO_fob_ARA,UCO (hydrotreating) fob ARA range,UCO_(hydrotreating)_fob_ARA,UCO cif ARA,UCO_cif_ARA
0,2026-04-23 00:00:00,prompt,3098.75,prompt,1529.96,prompt,1259.225,prompt,1265,prompt,1295,prompt,1140
1,2026-04-22 00:00:00,prompt,3142.72,prompt,1550.07,prompt,1259.815,prompt,1265,prompt,1295,prompt,1140
2,2026-04-21 00:00:00,prompt,2922.44,prompt,1561.5,prompt,1263.515,prompt,1245,prompt,1285,prompt,1140
3,2026-04-20 00:00:00,prompt,2858.88,prompt,1545,prompt,1272.685,prompt,1245,prompt,1285,prompt,1140
4,2026-04-17 00:00:00,prompt,2827.59,prompt,1552.95,prompt,1280.84,prompt,1245,prompt,1285,prompt,1130
...,...,...,...,...,...,...,...,...,...,...,...,...,...
1256,2021-04-30 00:00:00,prompt,1983.18,prompt,1609.77,prompt,1311.2,NaN,NaN,NaN,NaN,prompt,1210
1257,2021-04-29 00:00:00,prompt,1987.52,prompt,1607.19,prompt,1320.735,NaN,NaN,NaN,NaN,prompt,1190
1258,2021-04-28 00:00:00,prompt,1982.93,prompt,1605.45,prompt,1312.605,NaN,NaN,NaN,NaN,prompt,1190
1259,2021-04-27 00:00:00,prompt,1968.09,prompt,1591.75,prompt,1310.39,NaN,NaN,NaN,NaN,prompt,1175
1260,2021-04-26 00:00:00,prompt,1965.05,prompt,1568.95,prompt,1310.39,NaN,NaN,NaN,NaN,prompt,1175

In [11]:
#remove prompt columns
renewables_df = renewables_df.drop(columns = ['HVO (Class II) fob ARA range',
       'Ucome fob ARA range','UCO ex-works ARA range',
       'UCO fob ARA range',
       'UCO (hydrotreating) fob ARA range', 'UCO cif ARA',
       ])
renewables_df

,Date,HVO_class_II_fob_ARA,Ucome_fob_ARA,UCO_exw_ARA,UCO_fob_ARA,UCO_(hydrotreating)_fob_ARA,UCO_cif_ARA
0,2026-04-23 00:00:00,3098.75,1529.96,1259.225,1265,1295,1140
1,2026-04-22 00:00:00,3142.72,1550.07,1259.815,1265,1295,1140
2,2026-04-21 00:00:00,2922.44,1561.5,1263.515,1245,1285,1140
3,2026-04-20 00:00:00,2858.88,1545,1272.685,1245,1285,1140
4,2026-04-17 00:00:00,2827.59,1552.95,1280.84,1245,1285,1130
...,...,...,...,...,...,...,...
1256,2021-04-30 00:00:00,1983.18,1609.77,1311.2,NaN,NaN,1210
1257,2021-04-29 00:00:00,1987.52,1607.19,1320.735,NaN,NaN,1190
1258,2021-04-28 00:00:00,1982.93,1605.45,1312.605,NaN,NaN,1190
1259,2021-04-27 00:00:00,1968.09,1591.75,1310.39,NaN,NaN,1175
1260,2021-04-26 00:00:00,1965.05,1568.95,1310.39,NaN,NaN,1175

In [12]:
renewables_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1261 entries, 0 to 1260
Data columns (total 7 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   Date                         1261 non-null   object
 1   HVO_class_II_fob_ARA         1261 non-null   object
 2   Ucome_fob_ARA                1261 non-null   object
 3   UCO_exw_ARA                  1261 non-null   object
 4   UCO_fob_ARA                  1048 non-null   object
 5   UCO_(hydrotreating)_fob_ARA  207 non-null    object
 6   UCO_cif_ARA                  1261 non-null   object
dtypes: object(7)
memory usage: 69.1+ KB

### BRENT CRUDE OIL

In [ ]:
# leading fueleu Brent prices
brent_df = pd.read_excel('./data/raw/Price History_ICE_EUROPE_BRENT_CRUDE.xlsx')
brent_df

,ICE Europe Brent Crude Electronic Energy Future | Price History 29-Apr-2026 17:28,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCOc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Interval: Daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,History Period: 03-Jan-2010 - 28-Apr-2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4237,2010-01-08 00:00:00,81.37,-0.14,-0.001718,81.51,80.59,82.05,157485,124828,NaN,NaN,NaN,456519
4238,2010-01-07 00:00:00,81.51,-0.38,-0.00464,82,81.05,82.05,131284,144865,NaN,NaN,NaN,375912
4239,2010-01-06 00:00:00,81.89,1.3,0.016131,80.38,79.77,82.21,157872,163579,NaN,NaN,NaN,374353
4240,2010-01-05 00:00:00,80.59,0.47,0.005866,80.29,79.75,80.84,131754,172055,NaN,NaN,NaN,311672
4241,2010-01-04 00:00:00,80.12,NaN,NaN,78.49,78.34,80.48,122637,176882,NaN,NaN,NaN,273408

In [14]:
brent_df.head(30)

,ICE Europe Brent Crude Electronic Energy Future | Price History 29-Apr-2026 17:28,Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10,Unnamed: 11,Unnamed: 12
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,LCOc1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,Interval: Daily,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,History Period: 03-Jan-2010 - 28-Apr-2026,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,VAP: Total,990123595,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,Price,Volume,%Volume,Count,%Count,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,120.00 - 140.00,13136722,0.013268,74,0.017569,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
10,100.00 - 120.00,178731296,0.180514,955,0.226733,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,80.00 - 100.00,177593056,0.179365,722,0.171415,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,60.00 - 80.00,378011441,0.381782,1472,0.349478,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,40.00 - 60.00,206215949,0.208273,842,0.199905,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,20.00 - 40.00,35635529,0.035991,145,0.034425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
15,0.00 - 20.00,799602,0.000808,2,0.000475,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,LCOc1 Statistics Daily 04-Jan-2010 - 2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,Price,NaN,NaN,Volume,NaN,NaN,NaN,NaN,Up/Down,NaN,Price Change (Close-Close),NaN,NaN
20,High,139.13,2022-03-07 00:00:00,Max,1243109,2025-06-13 00:00:00,Advancing,510959062,Up,2187,Up,0.210186,2020-04-02 00:00:00
21,Low,15.98,2020-04-22 00:00:00,Min,5892,2022-09-30 00:00:00,Declining,475953628,Down,2013,Down,-0.244036,2020-04-21 00:00:00
22,Avg (Close),77.844192,NaN,Avg,234960.511391,NaN,Total,990123595,Unch,12,Period,0.388667,04-Jan-2010 - 28-Apr-2026
23,Avg (High-Low),77.555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
26,LCOc1 History Daily 04-Jan-2010 - 28-A...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
27,Exchange Date,Close,Net,%Chg,Open,Low,High,Volume,OI,Bid,Ask,Contract Month,Market Volume
28,2026-04-28 00:00:00,111.26,3.03,0.027996,107.82,107.81,112.7,143349,189829,111.17,111.34,202606,1335803
29,2026-04-27 00:00:00,108.23,2.9,0.027533,106.44,105.82,109.79,235075,214102,108.31,108.43,202606,1097448

In [15]:
brent_df = brent_df.iloc[28:,[0,1]]
brent_df.columns = ['Date', 'EU_BRENT_CRUDE']
brent_df.reset_index(drop=True, inplace=True)
brent_df

                     Date EU_BRENT_CRUDE
0     2026-04-28 00:00:00         111.26
1     2026-04-27 00:00:00         108.23
2     2026-04-24 00:00:00         105.33
3     2026-04-23 00:00:00         105.07
4     2026-04-22 00:00:00         101.91
...                   ...            ...
4209  2010-01-08 00:00:00          81.37
4210  2010-01-07 00:00:00          81.51
4211  2010-01-06 00:00:00          81.89
4212  2010-01-05 00:00:00          80.59
4213  2010-01-04 00:00:00          80.12

[4214 rows x 2 columns]

### LSMGO

In [ ]:
# get data on LSMGO
lsmgo_df = pd.read_excel('./data/raw/BKLSM-RDM-CLY (LSMGO Rotterdam) Price History.xlsx')

In [17]:
lsmgo_df.columns = ['Date', 'LSMGO_Rotterdam']
lsmgo_df = lsmgo_df.iloc[1:]

In [18]:
lsmgo_df

           Date LSMGO_Rotterdam
1    2026-04-30         1356.25
2    2026-04-29            1343
3    2026-04-28          1298.5
4    2026-04-27          1300.5
5    2026-04-24            1284
...         ...             ...
2850 2015-02-05           517.5
2851 2015-02-04           534.5
2852 2015-02-02           495.5
2853 2015-01-30           472.5
2854 2015-01-27           464.5

[2854 rows x 2 columns]

In [ ]:
# get data on the EUR/USD exchange rate
eur_usd_df = pd.read_excel('./data/raw/EUR_USD_rate.xlsx')
eur_usd_df

,Unnamed: 0,"Argus - Interactive Data Corp exchange rate EUR/USD day-ahead, London close, No Unit",Unnamed: 2
0,Date,Timing,Price
1,2026-04-23 00:00:00,day-ahead,0.8537
2,2026-04-22 00:00:00,day-ahead,0.8533
3,2026-04-21 00:00:00,day-ahead,0.8508
4,2026-04-20 00:00:00,day-ahead,0.8486
...,...,...,...
1284,2021-04-30 00:00:00,day-ahead,0.8313
1285,2021-04-29 00:00:00,day-ahead,0.8253
1286,2021-04-28 00:00:00,day-ahead,0.8266
1287,2021-04-27 00:00:00,day-ahead,0.828
1288,2021-04-26 00:00:00,day-ahead,0.828

In [20]:
eur_usd_df = eur_usd_df.iloc[1:,[0,2]]

In [21]:
eur_usd_df.columns = ['Date', 'EUR_USD_rate']
eur_usd_df.reset_index(drop=True, inplace=True)

In [22]:
eur_usd_df

                     Date EUR_USD_rate
0     2026-04-23 00:00:00       0.8537
1     2026-04-22 00:00:00       0.8533
2     2026-04-21 00:00:00       0.8508
3     2026-04-20 00:00:00       0.8486
4     2026-04-17 00:00:00       0.8471
...                   ...          ...
1283  2021-04-30 00:00:00       0.8313
1284  2021-04-29 00:00:00       0.8253
1285  2021-04-28 00:00:00       0.8266
1286  2021-04-27 00:00:00        0.828
1287  2021-04-26 00:00:00        0.828

[1288 rows x 2 columns]

### FED FUNDS DATA

In [ ]:
# get the FED funds rate
fed_funds_df = pd.read_excel('./data/raw/FEDFUNDS.xlsx')
fed_funds_df

/opt/anaconda3/lib/python3.13/site-packages/openpyxl/styles/stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

,Effective Date,Rate Type,Rate (%),1st Percentile (%),25th Percentile (%),75th Percentile (%),99th Percentile (%),Volume ($Billions),Target Rate From (%),Target Rate To (%),Intra Day - Low (%),Intra Day - High (%),Standard Deviation (%),30-Day Average SOFR,90-Day Average SOFR,180-Day Average SOFR,SOFR Index,Revision Indicator (Y/N),Footnote ID
0,05/01/2026,EFFR,3.64,3.60,3.63,3.64,3.70,115,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,04/30/2026,EFFR,3.64,3.60,3.63,3.65,3.70,90,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,04/29/2026,EFFR,3.64,3.60,3.64,3.65,3.70,87,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,04/28/2026,EFFR,3.64,3.60,3.64,3.65,3.70,82,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,04/27/2026,EFFR,3.64,3.60,3.63,3.65,3.70,85,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,05/07/2020,EFFR,0.05,0.04,0.05,0.05,0.15,92,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1502,05/06/2020,EFFR,0.05,0.04,0.05,0.05,0.15,90,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1503,05/05/2020,EFFR,0.05,0.03,0.05,0.05,0.15,92,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1504,05/04/2020,EFFR,0.05,0.03,0.05,0.05,0.15,90,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1505,05/01/2020,EFFR,0.05,0.03,0.04,0.05,0.15,92,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
fed_funds_df['Effective Date'] = fed_funds_df['Effective Date'].apply(lambda x: datetime.datetime.strptime(x, '%m/%d/%Y'))
fed_funds_df

,Effective Date,Rate Type,Rate (%),1st Percentile (%),25th Percentile (%),75th Percentile (%),99th Percentile (%),Volume ($Billions),Target Rate From (%),Target Rate To (%),Intra Day - Low (%),Intra Day - High (%),Standard Deviation (%),30-Day Average SOFR,90-Day Average SOFR,180-Day Average SOFR,SOFR Index,Revision Indicator (Y/N),Footnote ID
0,2026-05-01,EFFR,3.64,3.60,3.63,3.64,3.70,115,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2026-04-30,EFFR,3.64,3.60,3.63,3.65,3.70,90,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2026-04-29,EFFR,3.64,3.60,3.64,3.65,3.70,87,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,2026-04-28,EFFR,3.64,3.60,3.64,3.65,3.70,82,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,2026-04-27,EFFR,3.64,3.60,3.63,3.65,3.70,85,3.5,3.75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1501,2020-05-07,EFFR,0.05,0.04,0.05,0.05,0.15,92,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1502,2020-05-06,EFFR,0.05,0.04,0.05,0.05,0.15,90,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1503,2020-05-05,EFFR,0.05,0.03,0.05,0.05,0.15,92,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1504,2020-05-04,EFFR,0.05,0.03,0.05,0.05,0.15,90,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1505,2020-05-01,EFFR,0.05,0.03,0.04,0.05,0.15,92,0.0,0.25,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [25]:
fed_funds_df = fed_funds_df[['Effective Date', 'Rate (%)']]
fed_funds_df.columns = ['Date', 'Rate']
fed_funds_df

           Date  Rate
0    2026-05-01  3.64
1    2026-04-30  3.64
2    2026-04-29  3.64
3    2026-04-28  3.64
4    2026-04-27  3.64
...         ...   ...
1501 2020-05-07  0.05
1502 2020-05-06  0.05
1503 2020-05-05  0.05
1504 2020-05-04  0.05
1505 2020-05-01  0.05

[1506 rows x 2 columns]

In [26]:
fed_funds_df[fed_funds_df['Date'] == '2010-01-01']

Empty DataFrame
Columns: [Date, Rate]
Index: []

In [27]:
fed_funds_df['Date'][0]

Timestamp('2026-05-01 00:00:00')

In [28]:
fed_funds_df = fed_funds_df.iloc[666:]

In [29]:
fed_funds_df.reset_index(drop=True, inplace=True)
fed_funds_df

          Date  Rate
0   2023-09-01  5.33
1   2023-08-31  5.33
2   2023-08-30  5.33
3   2023-08-29  5.33
4   2023-08-28  5.33
..         ...   ...
835 2020-05-07  0.05
836 2020-05-06  0.05
837 2020-05-05  0.05
838 2020-05-04  0.05
839 2020-05-01  0.05

[840 rows x 2 columns]

In [ ]:
# import the FuelEU penalties dataset
fueleu_penalties_df = pd.read_excel('./data/raw/FuelEU_MGO_penalty.xlsx')
fueleu_penalties_df

,Unnamed: 0,"FuelEU MGO penalty USD/tCO2e, London close, USD/t CO2e",Unnamed: 2
0,Date,Timing,Price
1,2026-04-23 00:00:00,prompt,755.43
2,2026-04-22 00:00:00,prompt,755.78
3,2026-04-21 00:00:00,prompt,758
4,2026-04-20 00:00:00,prompt,759.97
...,...,...,...
327,2025-01-08 00:00:00,prompt,664.65
328,2025-01-07 00:00:00,prompt,668.51
329,2025-01-06 00:00:00,prompt,670.1
330,2025-01-03 00:00:00,prompt,663.76
331,2025-01-02 00:00:00,prompt,661.38

In [31]:
fueleu_penalties_df = fueleu_penalties_df.iloc[1:,[0,2]]
fueleu_penalties_df.columns = ['Date', 'FuelEU_MGO_penalty']
fueleu_penalties_df.reset_index(drop=True, inplace=True)
fueleu_penalties_df

                    Date FuelEU_MGO_penalty
0    2026-04-23 00:00:00             755.43
1    2026-04-22 00:00:00             755.78
2    2026-04-21 00:00:00                758
3    2026-04-20 00:00:00             759.97
4    2026-04-17 00:00:00             761.31
..                   ...                ...
326  2025-01-08 00:00:00             664.65
327  2025-01-07 00:00:00             668.51
328  2025-01-06 00:00:00              670.1
329  2025-01-03 00:00:00             663.76
330  2025-01-02 00:00:00             661.38

[331 rows x 2 columns]

In [32]:
for df in [renewables_df, brent_df, lsmgo_df, eur_usd_df, fed_funds_df, fueleu_penalties_df]:
    df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
    df['Date'] = df['Date'].dt.normalize()

/var/folders/z7/srrls_hs3992pkxm_8_3kvg00000gn/T/ipykernel_62344/460675082.py:2: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = pd.to_datetime(df['Date'], errors='coerce')
/var/folders/z7/srrls_hs3992pkxm_8_3kvg00000gn/T/ipykernel_62344/460675082.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Date'] = df['Date'].dt.normalize()

In [33]:
final_df = renewables_df.merge(brent_df, on='Date', how='outer')
final_df = final_df.merge(lsmgo_df, on='Date', how='outer')
final_df = final_df.merge(eur_usd_df, on='Date', how='outer')
final_df = final_df.merge(fed_funds_df, on='Date', how='outer')
final_df = final_df.merge(fueleu_penalties_df, on='Date', how='outer')

In [34]:
final_df = final_df[(final_df['Date'] >= '2021-04-26')&(final_df['Date'] <= '2026-04-23')]
final_df.reset_index(drop=True, inplace=True)

In [35]:
final_df

,Date,HVO_class_II_fob_ARA,Ucome_fob_ARA,UCO_exw_ARA,UCO_fob_ARA,UCO_(hydrotreating)_fob_ARA,UCO_cif_ARA,EU_BRENT_CRUDE,LSMGO_Rotterdam,EUR_USD_rate,Rate,FuelEU_MGO_penalty
0,2021-04-26,1965.05,1568.95,1310.39,NaN,NaN,1175,65.65,503,0.828,0.07,NaN
1,2021-04-27,1968.09,1591.75,1310.39,NaN,NaN,1175,66.42,516,0.828,0.07,NaN
2,2021-04-28,1982.93,1605.45,1312.605,NaN,NaN,1190,67.27,521,0.8266,0.07,NaN
3,2021-04-29,1987.52,1607.19,1320.735,NaN,NaN,1190,68.56,528,0.8253,0.06,NaN
4,2021-04-30,1983.18,1609.77,1311.2,NaN,NaN,1210,67.25,523,0.8313,0.05,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...
1299,2026-04-17,2827.59,1552.95,1280.84,1245,1285,1130,90.38,1177.5,0.8471,NaN,761.31
1300,2026-04-20,2858.88,1545,1272.685,1245,1285,1140,95.48,1156,0.8486,NaN,759.97
1301,2026-04-21,2922.44,1561.5,1263.515,1245,1285,1140,98.48,1133.25,0.8508,NaN,758
1302,2026-04-22,3142.72,1550.07,1259.815,1265,1295,1140,101.91,1225.75,0.8533,NaN,755.78
1303,2026-04-23,3098.75,1529.96,1259.225,1265,1295,1140,105.07,1252,0.8537,NaN,755.43

In [36]:
#drop unused columns
final_df = final_df.drop(columns=['UCO_fob_ARA', 'UCO_(hydrotreating)_fob_ARA', 'UCO_cif_ARA'])

In [37]:
final_df

,Date,HVO_class_II_fob_ARA,Ucome_fob_ARA,UCO_exw_ARA,EU_BRENT_CRUDE,LSMGO_Rotterdam,EUR_USD_rate,Rate,FuelEU_MGO_penalty
0,2021-04-26,1965.05,1568.95,1310.39,65.65,503,0.828,0.07,NaN
1,2021-04-27,1968.09,1591.75,1310.39,66.42,516,0.828,0.07,NaN
2,2021-04-28,1982.93,1605.45,1312.605,67.27,521,0.8266,0.07,NaN
3,2021-04-29,1987.52,1607.19,1320.735,68.56,528,0.8253,0.06,NaN
4,2021-04-30,1983.18,1609.77,1311.2,67.25,523,0.8313,0.05,NaN
...,...,...,...,...,...,...,...,...,...
1299,2026-04-17,2827.59,1552.95,1280.84,90.38,1177.5,0.8471,NaN,761.31
1300,2026-04-20,2858.88,1545,1272.685,95.48,1156,0.8486,NaN,759.97
1301,2026-04-21,2922.44,1561.5,1263.515,98.48,1133.25,0.8508,NaN,758
1302,2026-04-22,3142.72,1550.07,1259.815,101.91,1225.75,0.8533,NaN,755.78
1303,2026-04-23,3098.75,1529.96,1259.225,105.07,1252,0.8537,NaN,755.43

In [40]:
#Interpolates missing values
final_df['Date'] = pd.to_datetime(final_df['Date'])

final_df = final_df.set_index('Date')

final_df = final_df.asfreq('D')

final_df = final_df.reset_index()

final_df[final_df.columns.difference(['Date'])] = final_df[final_df.columns.difference(['Date'])].apply(pd.to_numeric, errors='coerce')

final_df = final_df.interpolate(method='linear')
final_df.fillna(0, inplace=True)
final_df

,Date,HVO_class_II_fob_ARA,Ucome_fob_ARA,UCO_exw_ARA,EU_BRENT_CRUDE,LSMGO_Rotterdam,EUR_USD_rate,Rate,FuelEU_MGO_penalty
0,2021-04-26,1965.05,1568.95,1310.390000,65.65,503.000000,0.8280,0.07,0.000000
1,2021-04-27,1968.09,1591.75,1310.390000,66.42,516.000000,0.8280,0.07,0.000000
2,2021-04-28,1982.93,1605.45,1312.605000,67.27,521.000000,0.8266,0.07,0.000000
3,2021-04-29,1987.52,1607.19,1320.735000,68.56,528.000000,0.8253,0.06,0.000000
4,2021-04-30,1983.18,1609.77,1311.200000,67.25,523.000000,0.8313,0.05,0.000000
...,...,...,...,...,...,...,...,...,...
1819,2026-04-19,2848.45,1547.65,1275.403333,93.78,1163.166667,0.8481,5.33,760.416667
1820,2026-04-20,2858.88,1545.00,1272.685000,95.48,1156.000000,0.8486,5.33,759.970000
1821,2026-04-21,2922.44,1561.50,1263.515000,98.48,1133.250000,0.8508,5.33,758.000000
1822,2026-04-22,3142.72,1550.07,1259.815000,101.91,1225.750000,0.8533,5.33,755.780000
1823,2026-04-23,3098.75,1529.96,1259.225000,105.07,1252.000000,0.8537,5.33,755.430000

In [41]:
final_df.to_csv('final_dataset.csv', index=False)